sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GXG/swILbn+L9+K7GkLyYw7nH5MAEzHSxXjD7S1jY+6458EEodgAvIxl/9EJgagaOeoGx/Yhk/YoV5CXrGeFR2AP8lIFiEQUNShnuS4k58mG/BBluCMg/WNHe5SS8OrfLCKpO5maUTC5XLDKjj+KKXHAgfIkdXNSgyn69XCmpMnxbP0w1scVikjmOq5u77En/dlpjfz/uhGNSPpiLG66hUBjcyI3nbRH/rTcwFddMiXwJeJquLjKYGPhuUi/T8F1aV5VFTSuTn5RY0aNgnGzZ5UVGxACZ8OLCzUobwt3LGt1yCkC+TprZ1A5xfgJjoq91UUnB05jtEtjqswMYkg2M5wr1dI8m+I9kJKcUMgn4KhFZ+JZBv504897uOXe4+q0/mvlg+wKnf3l13HK8YE8hldzm3yWLlAQLZ0/UvvA3Eg5uEAK9J5qkjrZfBAmx31eujCWnGFwLu0FiN68SsMVPoG7P0qqxckw/iPJjqU/f8bEHOnyV8SCgjy4KM1Dk6dXPvHYInSfOQFN9ruFk0Ima2diZGjpkMwbDabErKde1rD3WYySJp2ZmOY62XJVz7tFfZRStbZ91CQRQHA13bV1IBbo8KgFj/ygbh+pfrRNPl1IviuX4/zDTVJUX8tjbDrcflIeel4fQ7RDJTRxsWg7nN4JGWb2EzyJ5EWpXHrARAw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Iliad_2199
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy